# Generated by Django 5.0.6 on 2024-08-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_sales', '0003_customer_county_customer_sub_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
