# Generated by Django 5.0.6 on 2024-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_sales', '0002_alter_sale_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='location_of_use',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='metered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='specific_economic_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='type_of_use',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('Business', 'Business'), ('Other', 'Other')], default='Domestic', max_length=10),
        ),
    ]
