# Generated by Django 5.0.6 on 2024-08-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_sales', '0004_customer_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='place',
        ),
    ]
